name: core_location_fluttify_example
description: Demonstrates how to use the core_location_fluttify plugin.
publish_to: 'none'

environment:
  sdk: '>=3.9.2 <4.0.0'
  flutter: '>=3.35.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 
  core_location_fluttify:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
