name: core_location_fluttify
description: A new Flutter project.
version: 0.7.1
homepage: https://github.com/fluttify-project/core_location_fluttify
publish_to: none


environment:
  sdk: '>=3.9.2 <4.0.0'
  flutter: '>=3.35.0'

dependencies:
  flutter:
    sdk: flutter
  foundation_fluttify: 
    git: https://github.com/boomcx/foundation_fluttify

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.core_location_fluttify
        pluginClass: CoreLocationFluttifyPlugin
      ios:
        pluginClass: CoreLocationFluttifyPlugin